services:
  batch-movie-compressor:
    image: ghcr.io/HNRobert/batch-movie-compressor:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: batch-movie-compressor

    # Resource limits - adjust based on your hardware
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 8G

    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - FFMPEG_LOG_LEVEL=info
      - TARGET_SIZE=${TARGET_SIZE:-12.0}

    # Volume mounts - separate input and output directories
    volumes:
      # Mount your input movie directory to /data/in
      - '${INPUT_DIR:-./data/in}:/data/in'
      # Mount your output directory to /data/out
      - '${OUTPUT_DIR:-./data/out}:/data/out'

    # Working directory
    working_dir: /app

    # Default command - process movies from /data/in to /data/out
    command:
      [
        'python',
        'main.py',
        '/data/in',
        '/data/out',
        '--target-size',
        '${TARGET_SIZE:-12}',
      ]

    # Restart policy
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ['CMD', 'python3', '-c', 'import sys; sys.exit(0)']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Logging
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
# Example environment variables - create .env file
# INPUT_DIR=/path/to/your/original/movies
# OUTPUT_DIR=/path/to/compressed/movies
# TARGET_SIZE=12.0
